[background]
mode = "gradient"
color = "#413249"
dim_strength = 40

[background.gradient]
top_left = "#A85BFF"
top_right = "#39B8FF"
bottom_left = "#6FE2FF"
bottom_right = "#6F4CFF"

[lock]
user_hint = "Password"
show_username = true

[battery]
enabled = true

[weather]
enabled = false

[visuals.keyboard]
background_size = 46
background_color = "rgba(255, 255, 255, 0.05)"
color = "rgba(255, 255, 255, 0.68)"
size = 2
halign = "right"
valign = "top"
x = -24
y = 21

[visuals.battery]
background_color = "rgba(255, 255, 255, 0.05)"
background_size = 46
color = "rgba(255, 255, 255, 0.68)"
size = 20
halign = "right"
valign = "top"
x = -78
y = 21

[visuals.weather]
size = 2
temperature_color = "rgba(255, 255, 255, 0.73)"
location_color = "rgba(214, 227, 255, 0.58)"
temperature_size = 6
location_size = 3
icon_size = 40
temperature_font_family = "Geom"
temperature_font_weight = 600
temperature_letter_spacing = 0
location_font_family = "Google Sans Flex"
location_font_weight = 400
icon_gap = 1
location_gap = 1
icon_opacity = 80
left_padding = 30
bottom_padding = 30
alignment = "left"

[visuals.input]
background_color = "rgba(255, 255, 255, 0.08)"
border_color = "rgba(255, 255, 255, 0)"
width = 310
height = 54
radius = 10
mask_color = "#ffffff"
font_family = "Google Sans Flex"
font_weight = 400
font_size = 2
halign = "center"
valign = "center"
x = 0
y = 0

[visuals.avatar]
size = 160
background_color = "rgba(255, 255, 255, 0.08)"
placeholder_padding = 28
halign = "center"
valign = "center"
x = 0
y = 40

[visuals.username]
font_family = "Google Sans Flex"
font_weight = 400
color = "rgba(255, 255, 255, 0.84)"
size = 4
halign = "center"
valign = "center"
x = 0
y = 220

[visuals.clock]
format = "24h"
meridiem_size = 3
meridiem_offset_x = 6
meridiem_offset_y = 7
font_family = "Geom"
font_weight = 600
color = "rgba(255, 255, 255, 0.4)"
size = 14
halign = "center"
valign = "top"
x = 0
y = 40

[visuals.date]
color = "rgba(255, 255, 255, 0.4)"
font_family = "Geom"
font_weight = 600
size = 2
halign = "center"
valign = "top"
x = 0
y = 140

[visuals.placeholder]
color = "rgba(255, 255, 255, 0.9)"

[visuals.status]
rejected_color = "rgba(255, 213, 213, 0.88)"
pending_color = "rgba(236, 236, 236, 0.88)"
halign = "center"
valign = "bottom"
x = 0
y = -24

[visuals.eye]
color = "rgba(255, 255, 255, 0.72)"

[visuals.caps_lock]
color = "rgba(255, 255, 255, 0.52)"

[visuals.now_playing]
enabled = false
content_gap = 18
fade_duration_ms = 320
title_color = "rgba(255, 255, 255, 0.69)"
artist_color = "rgba(255, 255, 255, 0.39)"
title_size = 2
artist_size = 2
artwork_size = 44
artwork_radius = 8
right_padding = 52
bottom_padding = 56
artwork_opacity = 90
title_font_family = "Google Sans Flex"
title_font_weight = 400
artist_font_family = "Google Sans Flex"
artist_font_weight = 400
width = 380
text_gap = 10

[visuals.now_playing.background]
enabled = true
mode = "blur"
color = "rgba(0, 0, 0, 0.05)"
radius = 18
padding_x = 12
padding_y = 12
