[background]
mode = "gradient"
color = "#413249"
dim_strength = 40

[background.gradient]
top_left = "#A85BFF"
top_right = "#39B8FF"
bottom_left = "#6FE2FF"
bottom_right = "#6F4CFF"

[lock]
user_hint = "Password"
show_username = true

[weather]
enabled = false

[visuals.weather.icon]
size = 40
opacity = 80
halign = "left"
valign = "bottom"
x = 40
y = -122

[visuals.weather.temperature]
font_size = 6
font_family = "Geom"
font_weight = 600
letter_spacing = 0
color = "rgba(255, 255, 255, 0.73)"
halign = "left"
valign = "bottom"
x = 40
y = -76

[visuals.weather.location]
font_size = 3
font_family = "Google Sans Flex"
font_weight = 400
color = "rgba(214, 227, 255, 0.58)"
halign = "left"
valign = "bottom"
x = 40
y = -44

[visuals.input]
background_color = "rgba(255, 255, 255, 0.08)"
border_color = "rgba(255, 255, 255, 0)"
width = 310
height = 54
radius = 10
mask_color = "#ffffff"
font_family = "Google Sans Flex"
font_weight = 400
font_size = 2
halign = "center"
valign = "center"
x = 0
y = 80

[visuals.avatar]
size = 150
background_color = "rgba(255, 255, 255, 0.08)"
placeholder_padding = 28
halign = "center"
valign = "center"
x = 0
y = -120

[visuals.username]
font_family = "Google Sans Flex"
font_weight = 400
color = "rgba(255, 255, 255, 0.84)"
size = 4
halign = "center"
valign = "center"
x = 0
y = 0

[visuals.clock]
format = "24h"
meridiem_size = 3
meridiem_offset_x = 6
meridiem_offset_y = 7
font_family = "Geom"
font_weight = 600
color = "rgba(255, 255, 255, 0.4)"
size = 14
halign = "center"
valign = "top"
x = 0
y = 40

[visuals.date]
color = "rgba(255, 255, 255, 0.4)"
font_family = "Geom"
font_weight = 600
size = 2
halign = "center"
valign = "top"
x = 0
y = 140

[visuals.placeholder]
color = "rgba(255, 255, 255, 0.9)"

[visuals.status]
mode = "inline"
rejected_color = "rgba(255, 213, 213, 0.98)"
pending_color = "rgba(236, 236, 236, 0.88)"
halign = "center"
valign = "center"
x = 0
y = 135

[visuals.eye]
color = "rgba(255, 255, 255, 0.72)"

[visuals.caps_lock]
color = "rgba(255, 255, 255, 0.52)"


[visuals.now_playing]
enabled = true
fade_duration_ms = 320

[visuals.now_playing.artwork]
enabled = true
size = 44
radius = 8
opacity = 90
halign = "right"
valign = "bottom"
x = -388
y = -56

[visuals.now_playing.artist]
width = 318
color = "rgba(255, 255, 255, 0.39)"
font_family = "Google Sans Flex"
font_size = 2
font_weight = 400
halign = "right"
valign = "bottom"
x = -52
y = -84

[visuals.now_playing.title]
width = 318
color = "rgba(255, 255, 255, 0.69)"
font_family = "Google Sans Flex"
font_size = 2
font_weight = 400
halign = "right"
valign = "bottom"
x = -52
y = -60

[visuals.keyboard]
background_size = 46
background_color = "rgba(255, 255, 255, 0.05)"
color = "rgba(255, 255, 255, 0.68)"
size = 2
halign = "right"
valign = "top"
x = -24
y = 21

[battery]
enabled = true

[visuals.battery]
background_color = "rgba(255, 255, 255, 0.05)"
background_size = 46
color = "rgba(255, 255, 255, 0.68)"
size = 20
halign = "right"
valign = "top"
x = -78
y = 21

# Now Playing Background
[[visuals.backdrop]]
enabled = true
mode = "blur"
color = "rgba(255, 255, 255, 0.05)"
blur_strength = 12
radius = 10
border_color = "#FFFFFF18"
width = 390
height = 60
halign = "right"
valign = "bottom"
x = -50
y = -48
z = 0
