# Wallpaper source: https://wallhaven.cc/w/96wp7x
# Font: https://www.1001fonts.com/yoruka-font.html
[background]
mode = "file"
path = "/path/to/wallpaper.jpg"
color = "#49323E"
dim_strength = 20

[lock]
user_hint = "Password"
show_username = false

[visuals.layer]
enabled = true
style = "panel"
alignment = "center"
offset_x = -150
vertical_alignment = "center"
width = 540
height = 600
color = "rgba(0, 0, 0, 0)"
blur_radius = 0

[battery]
enabled = true

[weather]
enabled = false

[visuals.clock]
format = "12h"
style = "standard"
meridiem_size = 3
meridiem_offset_x = 6
meridiem_offset_y = 7
font_family = "Yoruka"
font_weight = 400
color = "rgba(255, 255, 255, 0.8)"
size = 20
halign = "center"
valign = "center"
x = 0
y = -110

[visuals.date]
font_family = "Yoruka"
font_weight = 400
color = "rgba(255, 255, 255, 0.9)"
size = 3
halign = "center"
valign = "center"
x = 0
y = 12

[visuals.input]
center_in_layer = true
horizontal_padding = 0
vertical_padding = 0
offset_x = 0
offset_y = 20
background_color = "rgba(255, 255, 255, 0.2)"
border_color = "rgba(255, 255, 255, 0.2)"
border_width = 3
width = 310
height = 54
radius = 50
mask_color = "#ffffff"
font_family = "Google Sans Flex"
font_weight = 400
font_size = 2

[visuals.status]
rejected_color = "#FF4D4D"
pending_color = "#FFFFFF"

[visuals.placeholder]
color = "rgba(255, 255, 255, 0.95)"

[visuals.eye]
color = "rgba(255, 255, 255, 0.72)"

[visuals.caps_lock]
color = "rgba(255, 255, 255, 0.52)"

[visuals.avatar]
enabled = false

[visuals.username]
enabled = false

[visuals.keyboard]
background_size = 46
background_color = "rgba(255, 255, 255, 0.1)"
color = "rgba(255, 255, 255, 0.9)"
size = 2
top_offset = -28
right_offset = 8

[visuals.battery]
background_color = "rgba(255, 255, 255, 0.1)"
background_size = 46
color = "rgba(255, 255, 255, 0.9)"
size = 20
top_offset = -28
right_offset = 8
gap = 8

[visuals.weather]
temperature_color = "rgba(255, 255, 255, 0.73)"
location_color = "rgba(214, 227, 255, 0.58)"
temperature_size = 6
location_size = 3
icon_size = 40
temperature_font_family = "Geom"
temperature_font_weight = 600
temperature_letter_spacing = 0
location_font_family = "Google Sans Flex"
location_font_weight = 400
icon_gap = 1
location_gap = 1
icon_opacity = 80
left_padding = 30
bottom_padding = 30
alignment = "left"

[visuals.now_playing]
enabled = false
content_gap = 18
fade_duration_ms = 320
title_color = "rgba(255, 255, 255, 0.52)"
artist_color = "rgba(255, 255, 255, 0.61)"
title_size = 2
artist_size = 2
artwork_size = 44
artwork_radius = 8
right_padding = 48
bottom_padding = 48
right_offset = 0
bottom_offset = 0
artwork_opacity = 90
title_font_family = "Google Sans Flex"
title_font_weight = 400
artist_font_family = "Google Sans Flex"
artist_font_weight = 400
width = 380

[visuals.now_playing.background]
enabled = true
mode = "blur"
color = "rgba(0, 0, 0, 0.05)"
radius = 18
padding_x = 12
padding_y = 12
