# Wallpaper source: https://wallhaven.cc/w/k81oj1
[background]
mode = "file"
path = "/path/to/wallpaper.jpg"
color = "#333249"
blur_radius = 0

[lock]
user_hint = "Password"
show_username = false

[battery]
enabled = true

[weather]
enabled = false

[visuals.clock]
format = "12h"
style = "standard"
meridiem_size = 3
meridiem_offset_x = 6
meridiem_offset_y = 7
font_family = "Geom"
font_weight = 600
color = "#A6AECD66"
size = 20
halign = "center"
valign = "center"
x = 0
y = -30

[visuals.date]
font_family = "Google Sans Flex"
font_weight = 400
color = "#A6AECDB8"
size = 3
halign = "center"
valign = "center"
x = 0
y = 52

[visuals.input]
background_color = "#A6AECD0F"
border_color = "#FFFFFF0A"
border_width = 3
width = 310
height = 54
radius = 50
mask_color = "#ffffff"
font_family = "Google Sans Flex"
font_weight = 400
font_size = 2

[visuals.status]
rejected_color = "#FFD5D5"
pending_color = "#ECECEC"

[visuals.placeholder]
color = "#A6AECD99"

[visuals.avatar]
enabled = false

[visuals.username]
enabled = false

[visuals.keyboard]
background_size = 46
background_color = "rgba(166, 174, 205, 0.05)"
color = "rgba(255, 255, 255, 0.68)"
size = 2
halign = "right"
valign = "top"
x = -24
y = 13

[visuals.battery]
background_color = "rgba(166, 174, 205, 0.05)"
background_size = 46
color = "rgba(255, 255, 255, 0.68)"
size = 20
halign = "right"
valign = "top"
x = -78
y = 13

[visuals.weather]
enabled = true

[visuals.weather.icon]
size = 40
opacity = 50
halign = "left"
valign = "bottom"
x = 30
y = -112

[visuals.weather.temperature]
font_size = 6
font_family = "Geom"
font_weight = 600
letter_spacing = 0
color = "#A6AECD74"
halign = "left"
valign = "bottom"
x = 30
y = -66

[visuals.weather.location]
font_size = 3
font_family = "Google Sans Flex"
font_weight = 400
color = "#D6E3FF5C"
halign = "left"
valign = "bottom"
x = 30
y = -34

[visuals.now_playing]
enabled = false
fade_duration_ms = 320

[visuals.now_playing.artwork]
enabled = true
size = 44
radius = 8
opacity = 90
halign = "right"
valign = "bottom"
x = -384
y = -48

[visuals.now_playing.artist]
width = 318
color = "rgba(255, 255, 255, 0.61)"
font_family = "Google Sans Flex"
font_size = 2
font_weight = 400
halign = "right"
valign = "bottom"
x = -48
y = -80

[visuals.now_playing.title]
width = 318
color = "#A6AECDAF"
font_family = "Google Sans Flex"
font_size = 2
font_weight = 400
halign = "right"
valign = "bottom"
x = -48
y = -48
